config/routes.rb
Rails.application.routes.draw do
  get 'question/new'
  get 'question/create'
  get 'answer/new'
  get 'answer/create'
  get 'answer/index'
  root to: 'pages#home'

  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'signup' }

  get 'users/index'
  get 'funding_rounds/interested'
  post "/users/:user_id/funding_rounds", to: "funding_rounds#create", as: "create_new_funding"
  post "/users/:user_id/funding_rounds/:funding_round_id/questions", to: "questions#create", as: "create_new_question"


  resources :funding_rounds, only: [:index]

  resources :users, only: [:show, :edit, :update, :index] do
    collection do
      get "startups"
      get "investors"
    end
    resources :funding_rounds, only: [:new, :create, :index] do
      member do
        post 'interested'
      end
      resources :answers, only: [:new, :index]
      resources :questions, only: [:new, :create, :index]
      resources :investments, only: [:index] do
        resources :answers, only: [:create]
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :investment
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funding_round.rb
class FundingRound < ApplicationRecord
belongs_to :user
has_many :investments, dependent: :destroy
has_many :questions, dependent: :destroy

validates :name, presence: true
validates :amount, presence: true
validates :name, uniqueness: { scope: :user_id}
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  belongs_to :funding_round
  has_many :answers, dependent: :destroy

  validates :interested, inclusion: { in:[true, false] }
  validates :user_id, uniqueness: { scope: :funding_round_id }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :funding_round

  def answer(question)
      Answer.where("question_id = #{question.id}").first.answer
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :investments, dependent: :destroy
  has_many :funding_rounds, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description_and_industry_and_url,
    against: [ :name, :description, :industry, :url ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    # t.string "role"
    # t.string "name"
    # t.string "description"
    # t.string "industry"
    # t.string "url"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :role, :name, :description, :industry, presence: true
  validates :role, inclusion: { in:["startup", "investor"] }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to users_path
    else
      render :new
    end
  end

  def index
    @answer = Answer.all
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params 
    params.require(:answer).permit(:answer)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @funding_round = FundingRound.find(params[:funding_round_id])
    @questions = @funding_round.questions
    @investment = Investment.new(interested: false, user: current_user, funding_round: @funding_round)
    @investment.save
  end

  def create
    params.each do |key, value|
      if key.match?(/question/) == true
        @answer = Answer.new()
        @answer.investment_id = params[:investment_id]
        @answer.question_id = key.rpartition('-').last
        @answer.answer = value
        @answer.save
      end
    end

    if @answer.save
      @investment = Investment.find(params[:investment_id])
      @investment.interested = true
      if @investment.save
        redirect_to user_path(current_user)
      else
        render :new
      end
    else
      render :new
    end
  end

  def index
    @answer = Answer.all
  end

  def answer
    self.answer
  end

  private
  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name, :description, :industry, :photo, :url, :address, :latitude, :longitude])
  end

  private


  def after_new_user_registration_path_for(resource)
    "/users/#{current_user.id}"
  end
end

app/controllers/funding_rounds_controller.rb
class FundingRoundsController < ApplicationController
  def new
    @funding_round = FundingRound.new
    @question = Question.new
  end

  def create
    @funding_round = FundingRound.new(funding_round_params)
    @funding_round.user_id = current_user.id
    if @funding_round.save
      redirect_to new_user_funding_round_question_path(current_user, @funding_round)
    else
      render :new
    end
  end

  def index
    @funding_rounds = FundingRound.all
  end

  def interested
    session[:return_to] ||= request.referer

    @investment = Investment.new(user_id: current_user.id, funding_round_id:params[:id], interested: true)
    @investment.save

    redirect_to session.delete(:return_to)
  end

  private

  def set_funding_round
    @funding_round = FundingRound.find(params[:id])
  end

  def funding_round_params
    params.require(:funding_round).permit(:name, :amount)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  def index
    @investments = Investment.where("user_id = params[:user_id] and funding_round_id = params[:funding_round_id]")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
    @questions = Question.where("funding_round_id = #{params[:funding_round_id]}")
  end

  def create
    @question = Question.new(question_params)
    @question.funding_round_id = params[:funding_round_id]

    if @question.save
      redirect_to new_user_funding_round_question_path
    else
      render :new
    end
  end

  def index
    @funding_round = FundingRound.find(params[:funding_round_id])
    @investments = @funding_round.investments
    @investments_ids = @funding_round.investments.ids
    @answers = Answer.all
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:question)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:startups, :investors]
  def show
    set_user
    @funding_rounds = @user.funding_rounds
    @investments = Investment.where("user_id = #{@user.id}")
  end

  def edit
    set_user
  end

  def update
    set_user

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def index
    @startups = User.where("role = 'startup'")
    @investors = User.where("role = 'investor'")
  end

  def startups
    if params[:query].present?
      @startups = User.search_by_name_and_description_and_industry_and_url(params[:query])
    else
      @startups = User.where("role = 'startup'")
    end
    @markers = @startups.geocoded.map do |startup|
      {
        lat: startup.latitude,
        lng: startup.longitude
      }
  end
end

  def investors
    if params[:query].present?
      @investors = User.search_by_name_and_description_and_industry_and_url(params[:query])
    else
      @investors = User.where("role = 'investor'")
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role, :name, :description, :industry, :photo, :address, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<h1>Answer#index</h1>
<p>Find me in app/views/answer/index.html.erb</p>

app/views/answers/new.html.erb
<h2 class="page-title">Application</h2>

<h4 class="page-subtitle">Let the startup know why to pick you:</h4>
<div class="container-centered">
  <% if @questions.empty? %>
      <% if Investment.where("user_id = #{current_user.id} and funding_round_id = #{@funding_round.id}").empty? %>
        <div class="button">
          <%= link_to "Interested", interested_user_funding_round_path(current_user.id, @funding_round), method: :post %>
        </div>
      <% else %>
        <div class="button-inactive">
          <p>Application done</p>
        </div>
      <% end %>
  <% else %>  
    <%= simple_form_for(@answer, method: :post, url: user_funding_round_investment_answers_path(current_user, @funding_round, @investment.id)) do |f| %>
      <%= f.error_notification %>
      <% @questions.each do |question| %>
        <p><%= question.question %></p>
        <div class="form-inputs container-md">
          <%= f.input :answer, required: true, label: false, input_html: { name: "question-#{question.id}" } %>
        </div>
      <% end %>
      <div class="button">
        <%= f.button :submit, "Apply now" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/funding_rounds/index.html.erb
<h2 class="page-title">Investment Opportunities</h2>

<h4 class="page-subtitle">Find all the active investment rounds from our startups</h4>

<% @funding_rounds.each do |funding_round| %>
<div class="card mt-3 mb-5 ml-3 mr-3" style="max-width: 2000px;">
  <div class="row no-gutters d-flex align-items-center">
      <div class="col-md-3">
      <% if funding_round.user.photo.present? %>
        <%= cl_image_tag funding_round.user.photo.key, :class => "card-img p-2" %>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title"><strong><%= funding_round.user.name %> - <%= funding_round.name %></strong></h5>
        <p class="industrycard"><strong>Industry:</strong> <%= funding_round.user.industry %></p>
        <p class="card-text"><strong>Amount:</strong> <%= funding_round.amount %><%= " USD" %></p>
      </div>
    </div>
    <div class="col-md-3">
        <% if Investment.where("user_id = #{current_user.id} and funding_round_id = #{funding_round.id}").empty? %>
        <div class="button">
          <%= link_to "Apply to Invest", new_user_funding_round_answer_path(current_user.id, funding_round) %>
        </div>
        <% else %>
        <div class="button-inactive">
          <p>Application done</p>
        </div>
        <% end %>
        <div class="button">
          <%= link_to "Startup Profile", user_path(funding_round.user) %>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/funding_rounds/new.html.erb
<h2 class="page-title">Funding round</h2>

<h4 class="page-subtitle">Add your new funding round below</h4>

<div class="container-md">
 
  <%= simple_form_for(@funding_round, method: :post, url: create_new_funding_path) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name,
                    required: true %>
      <%= f.input :amount,
                    required: true %>
      <div class="button">
        <%= f.button :submit, "Save Funding Round" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Investars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes'%>
      <div class="wrapper">
        <%= yield %>  
        <div class="push"></div>
      </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header" style="background-image: url(https://res.cloudinary.com/doewieec6/image/upload/v1598454330/Rectangle_1_em8j4l.png);">
  <%= image_tag ("header.png"), :class => "mt-5 img-fluid" %>
</div>

<div class="container">

  <h2 class="title">Investar</h2>
  <h4 class="subtitle">Your  plattform for exclusive investment opportunities</h4>
    <div class="container-valueprops">
      <div class="valueprops">
        <div class="row">
          <div class="col-sm-12 col-md-4">
            <%= image_tag ("head_icon.png"), style: "width: 140px; height: 120px; margin: 20px;" %>
            <h4>Screen</h4>
            <p>Find the perfect business opportunity</p>
          </div>
          <div class="col-sm-12 col-md-4">
            <%= image_tag ("connect_icon.png"), style: "width: 140px; height: 120px; margin: 20px;" %>
            <h4>Match</h4>
            <p>Find the perfect business opportunity</p>
          </div>
          <div class="col-sm-12 col-md-4">
            <%= image_tag ("plant_icon.png"), style: "width: 180px; height: 120px; margin: 20px;" %>
            <h4>Earn</h4>
            <p>Find the perfect business opportunity</p>
          </div>
        </div>
    </div>
  </div>

  <div class="button">
    <%= link_to "Sign Up", new_user_registration_path %>
  </div>
</div>

<p class="quote">
“Innovation is the ability to see change as an opportunity – not a threat.”
Steve Jobs
</p>

<div class="banner_img">
  <%= image_tag("startup_banner2.jpg", style: "width: 100%; max-height: 700px; object-fit: cover;") %>
</div>

app/views/question/new.html.erb
<h5></h5>
    <%= simple_form_for(@question) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs container-small">
      <%= f.input :question,
                    required: true %>
      <div class="button">
        <%= f.button :submit, "Save Question" %>
      </div>
    </div>
 <% end %>

app/views/questions/create.html.erb
<h1>Question#create</h1>
<p>Find me in app/views/question/create.html.erb</p>

app/views/questions/index.html.erb
<h2 class="page-title"><%= @funding_round.name %></h2>

<div class="container">
  <div class="row">
    <div class="col-12">
      <% @investments.each do |investment| %>
        <div class="card mt-3 mb-5 ml-3 mr-3" style="max-width: 2000px;">
          <div class="row no-gutters d-flex align-items-center">
            <div class="col-lg-4 investor-photo">
              <% if investment.user.photo.present? %>
                <%= cl_image_tag investment.user.photo.key, :class => "card-img" %>
              <% end %>
            </div>
            <div class="col-lg-5">
              <div class="card-body">
                <h5 class="card-title"><%= investment.user.name %></h5>
                <% investment.funding_round.questions.each do |question| %>
                  <p><strong><%= question.question %></strong></p>
                  <p><% if question.answer(question).nil? == false %>
                  <%= question.answer(question) %>
                  <% end %>
                  </p>
                <% end %>
                <p class="card-text"></p>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="button investor-button">
                <%= link_to "Investor Profile", user_path(investment.user.id) %>
              </div>
              <div class="button investor-button">
                <%= link_to "Accept Application", user_path(investment.user.id) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container-md">
  <h2 class="page-title">Question</h2>
  <h4 class="page-subtitle">Which question do you want to ask your potential investors?</h4>

  <div class="d-flex justify-content-around align-items-end">

    <div class="question-input">
      <%= simple_form_for(@question, method: :post, url: create_new_question_path) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :question,
                      required: true %>
        <div class="button-md">
          <%= f.button :submit, "Save Question" %>
        </div>
      </div>
      <% end %>
    </div>

    <% if @questions.empty? == false %>
      <div class="question-box">
        <ol>
          <% @questions.each do |question| %>
            <li><%= question.question%></li>
          <% end %>
        </ol>
        <div class="button-md">
          <%= link_to "Save Form", user_path(current_user)%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/shared/_button.html.erb
<div class="button">
  <p>Sign in</p>
</div>

app/views/shared/_card.html.erb
<div class="card mt-3 mb-5 ml-3 mr-3" style="max-width: 2000px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="https://images.unsplash.com/photo-1559024094-4a1e4495c3c1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
      <p class="industrycards d-flex justify-content-end"><strong>Industry</strong></p>
        <h5 class="card-title">Card title</h5>
        <p class="industrycard"><strong>Description</strong></p>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="far fa-copyright"></i> Investars. All rights reserved.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <%= image_tag("logo.png", style: "width: 50px;") %>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Investors", investors_users_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Startups", startups_users_path, :class => "nav-link" %>
      </li>
      <% if user_signed_in? == false %>
      <li class="nav-item active">
        <div class="button_small">
          <%= link_to "Login", new_user_session_path %>
        </div>
      </li>
      <% end %>
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag(current_user.photo.key, :class=>"avatar dropdown-toggle border", :id=>"navbarDropdown", "data-toggle"=>"dropdown", "aria-haspopup" => "true","aria-expanded" =>"false", :transformation=>[
              {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"}, {:width=>200, :crop=>"scale"}])%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", user_path(current_user) , :class => "dropdown-item" %>
                <%= link_to "Log-Out", destroy_user_session_path ,method: :delete, :class => "dropdown-item" %>
          <% else %>
            <%= image_tag("profile.png", :class=>"avatar dropdown-toggle border", :id=>"navbarDropdown", "data-toggle"=>"dropdown", "aria-haspopup" => "true","aria-expanded" =>"false", :transformation=>[
              {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"}, {:width=>200, :crop=>"scale"}])%>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", user_path(current_user) , :class => "dropdown-item" %>
                <%= link_to "Log-Out", destroy_user_session_path ,method: :delete, :class => "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="page-title">Profile Update</h2>

<h4 class="page-subtitle">Change your profile</h4>

<div class="container-sm">

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :role,
                required: true,
                :collection => ["startup", "investor"] %>
    <%= f.input :name,
                required: true %>
    <%= f.input :description,
                required: true %>
    <%= f.input :industry,
                required: true %>
    <%= f.input :address,
                required: true %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class=button>
  <div class="form-actions">
    <%= f.button :submit, "Save Profile" %>
  </div>
  </div>
</div>
<% end %>

app/views/users/investors.html.erb
<h2 class="page-title">Investors</h2>

<h4 class="page-subtitle">Our very experienced investors</h4>


<div class="container">
  <%= form_tag investors_users_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a investor"
          %>
        <% end %>
  <div class="row">
    <div class="col-12">
      <%= submit_tag "Search", class: "button-z" %>
      <% @investors.each do |investor| %>
        <div class="card mt-3 mb-5" style="max-width: 2000px;">
          <div class="row no-gutters d-flex align-tiems-center">
            <div class="col-lg-4 investor-photo">
              <% if investor.photo.present? %>
                <%= cl_image_tag investor.photo.key, :class => "card-img" %>
              <% end %>
            </div>
            <div class="col-lg-5">
              <div class="card-body">
                <h5 class="card-title"><%= investor.name %></h5>
                <p class="card-text"><%= investor.description.slice(0..100)%><% if investor.description.length >= 100 %> <%= "..." %><%end%></p>
                <p class="industrycard">Industry: <%= investor.industry %></p>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="button investor-button">
                <%= link_to "Investor Profile", user_path(investor) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="profile d-flex justify-content-start align-items-center">
  <div class="profile-picture">
    <% if @user.photo.present? %>  
      <%= cl_image_tag(@user.photo.key, :class => "profile-picture-image ml-4 mb-4 shadow") %>
    <% end %>
    <div class = "profile-button ml-4">
      <% if current_user.id == @user.id %>
      <% if current_user.role == 'startup' %>
        <div class="button_small">
          <%= link_to "Request Investment", new_user_funding_round_path(@user), style: "color: white; text-align: center;" %>
        </div>
        <div class="button_small">
          <%= link_to "Edit", edit_user_path(@user) %>
        </div>
      <% else current_user.role == 'investor' %>
        <div class="button_small">
          <%= link_to "Investment Opportunities", funding_rounds_path, style: "color: white; text-align: center;" %>
        </div>
        <div class="button_small">
          <%= link_to "Edit", edit_user_path(@user) %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="profile-text p-4">
      <h2><%= @user.name %></h2>
      <p><%= @user.description %></p>
      <div style="text-decoration: none">
        <ul style="list-style-type: none; padding: 0px;">
          <li><strong>Industry: </strong> <%= @user.industry %></li>
          <li><strong>Website: </strong> <%= @user.industry %></li>
          <li><strong>Address: </strong> <%= @user.address %></li>
        </ul>
      </div>
    </div>
  </div>

<div class="mt-5">
  <% if @user.role == "startup" %>
  <% if @funding_rounds.length > 0 %>
    <h3 style="text-align: left; padding: 20px; color: #F6AF42; border-bottom: 1px solid #F6AF42; padding-bottom: 5px;">Founding Rounds</h3>
    <% @funding_rounds.each do |funding_round| %>
      <div class="card mt-3 mb-5 ml-3 mr-3" style="max-width: 2000px;">
        <div class="row no-gutters d-flex align-items-center">
          <div class="col-lg-4 user-photo">
            <% if funding_round.user.photo.present? %>
              <%= cl_image_tag funding_round.user.photo.key, :class => "card-img" %>
            <% end %>
          </div>
          <div class="col-lg-5">
            <div class="card-body">
              <h5 class="card-title"><strong><%= funding_round.user.name %> - <%= funding_round.name %></strong></h5>
              <p class="industrycard"><strong>Industry:</strong> <%= funding_round.user.industry %></p>
              <p class="card-text"><strong>Amount:</strong> <%= funding_round.amount %> USD</p>
            </div>
          </div>
          <div class="col-md-3">
          <% if funding_round.investments.length > 0 %>
            <div class="button">
              <%=link_to "See Applications (#{funding_round.investments.length})", user_funding_round_questions_path(@user, funding_round)%>
            </div>
            <% else %>
            <div class="button-inactive">
              <p>No Application</p>
            </div>
            <% end %>
        </div>
      </div>
      </div>
    <% end %>
    <% end %>

  <% elsif @user.role == "investor" %>
  <% if @investments.length > 0 %>
  <h3 style="text-align: left; padding: 20px; color: #F6AF42; border-bottom: 1px solid #F6AF42; padding-bottom: 5px;">Your Funding Applications</h3>
  <% @investments.each do |investment| %>
      <div class="card mt-3 mb-5 ml-3 mr-3" style="max-width: 2000px;">
        <div class="row no-gutters d-flex align-items-center">
          <div class="col-lg-4 user-photo">
            <% if investment.funding_round.user.photo.present? %>
              <%= cl_image_tag investment.funding_round.user.photo.key, :class => "card-img p-2" %>
            <% end %>
          </div>
          <div class="col-lg-5">
            <div class="card-body">
              <h5 class="card-title"><strong><%= investment.funding_round.user.name %> - <%= investment.funding_round.name %></strong></h5>
              <p class="industrycard"><strong>Industry:</strong> <%= investment.funding_round.user.industry %></p>
              <p class="card-text"><strong>Amount:</strong> <%= investment.funding_round.amount %> USD</p>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="button-inactive">
              <p>Application done</p>
            </div>
         </div>
       </div>
      </div>
    <% end %>
    <% end %>
  <% end %>
</div>
</div>

app/views/users/startups.html.erb
<h2 class="page-title">Startups</h2>

<h4 class="page-subtitle">Our startups surprise with their innovation potential</h4>


<div class="container">
  <%= form_tag startups_users_path, method: :get do%>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a startup"
          %>
        <% end %>
        <%= submit_tag "Search", class: "button-z" %>
  <div class="row">
    <div class="col-12">
      <% @startups.each do |startup| %>
        <div class="card mt-3 mb-5" style="max-width: 2000px;">
          <div class="row no-gutters d-flex align-tiems-center">
            <div class="col-lg-4 investor-photo">
              <% if startup.photo.present? %>
                <%= cl_image_tag startup.photo.key, :class => "card-img" %>
              <% end %>
            </div>
            <div class="col-lg-5">
              <div class="card-body">
                <h5 class="card-title"><%= startup.name %></h5>
                <p class="industrycard"><strong><%= startup.industry %></strong></p>
                <p class="card-text"><%= startup.description.slice(0..100)%><% if startup.description.length >= 100 %> <%= "..." %><%end%></p>
                <p class="industrycard">Industry: <%= startup.industry %></p>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="button investor-button">
                <%= link_to "Startup Profile", user_path(startup) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div id="map"
      class ="map"
     style="width: 100%; height: 300px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>